#!/bin/bash
#PBS -N oe_BME
#PBS -l select=1:ncpus=1:mem=10gb,walltime=20:00:00
#PBS -j oe
#PBS -J 1-50

echo "START ------------------------------"

module add anaconda
source activate r_env_360
##lib_r360='.libPaths(c('~/.conda/envs/r_env_360/lib', .libPaths()))'
src='/panicle/ssapkot/GrainComp/'
#
DESIGN_FILE='/panicle/ssapkot/git_repo/GrainComp_GS/scripts/Design_File/SAP_BMT_EnvSeed.txt'
DESIGN=$(cat ${DESIGN_FILE} | head -n ${PBS_ARRAY_INDEX} | tail -n 1)
#
IFS=',' read -ra ARRAY <<< "${DESIGN}"
#
ENV="${ARRAY[0]}"
SEED="${ARRAY[1]}"
###MODEL="${ARRAY[1]}"
#
###Rscript  <$src/scripts/CV_Bayesian_BGLR.R
export LD_LIBRARY_PATH=/home/ssapkot/.conda/envs/r_env_360/lib/:$LD_LIBRARY_PATH

R -e "

library(BMTME)
setwd('/scratch2/ssapkot/GrainComp/')
pop <- 'SAP'
load('/panicle/ssapkot/git_repo/GrainComp_GS/data/SAP_BMTME.RData')
setwd(pop)
dir.create('BMT')
setwd('BMT')
pheno <- phenoBME

#Matrix design
LG <- cholesky(geno)
ZG <- model.matrix(~0 + as.factor(pheno\$Taxa))
Z.G <- ZG %*% LG
#Pheno data
#traits <- c('Amylose','Protein','Cal.g','Fat','Starch')
env <- colnames(pheno)
ENV <- \"${ENV}\"
iter <- \"${SEED}\"

#for (i in 1:length(traits)){
#       trait <- traits[i]
#        trait <- 'GrossEnergy'
        
        cols <- grep(ENV, env)
        Y <- as.matrix(pheno[cols])

        # Check fitting
        #fm <- BME(Y = Y, Z1 = Z.G, nIter = 100, burnIn = 10, thin = 1, bs = 0)

        # Check predictive capacities of the model with CrossValidation object
        pheno <- data.frame(GID = phenoBME[, 1], Env = '', Response = Y[, 1])
        CrossV <- CV.KFold(pheno, K=5, set_seed = iter)
        pm <- BME(Y = Y, Z1 = Z.G, nIter = 20000, burnIn = 10000, thin = 1, testingSet = CrossV)

        saveRDS(pm, file=paste0(pop,'_BMT_CV5_',trait,'_',iter,'.rds'))
        res <- summary(pm, information='complete')
        write.csv(res, file=paste0(pop,'_',trait,'_',iter,'_BMT.csv'), row.names=FALSE)
#    }
"
echo "Finish__________________"

