#!/bin/bash
#PBS -N oe_BMORS
#PBS -l select=1:ncpus=1:mem=5gb,walltime=12:00:00
#PBS -j oe


echo "START ------------------------------"

module add anaconda
source activate r_env_360
##lib_r360='.libPaths(c('~/.conda/envs/r_env_360/lib', .libPaths()))'
src='/panicle/ssapkot/GrainComp/'
#
#DESIGN_FILE='/panicle/ssapkot/git_repo/GrainComp_GS/scripts/Design_File/CV_seeds.txt'
#DESIGN=$(cat ${DESIGN_FILE} | head -n ${PBS_ARRAY_INDEX} | tail -n 1)
#
#IFS=',' read -ra ARRAY <<< "${DESIGN}"
#SEED="${ARRAY[0]}"
#TRAIT="${ARRAY[0]}"
###MODEL="${ARRAY[1]}"
#
###Rscript  <$src/scripts/CV_Bayesian_BGLR.R
export LD_LIBRARY_PATH=/home/ssapkot/.conda/envs/r_env_360/lib/:$LD_LIBRARY_PATH

R -e "

#.libPaths(c('/home/ssapkot/.conda/envs/r_env_360/lib', .libPaths()))

##install.packages('BMTME',repos='http://cran.us.r-project.org', dependencies = TRUE)
library(BGLR)
library(doMC)
library(foreach)
library(BMTME)

setwd('/panicle/ssapkot/git_repo/GrainComp_GS/')

#load('data/SAP_BMTME_GrainComp.RData') #SAP data
load('data/SAP_BMTME.RData') #SAP data
setwd('results/BMORS/')
pheno = phenoBMTME

#iter = \"${SEED}\"

pop <- 'SAP'

dir.create(paste0(pop))
setwd(paste0(pop))

taxa <- unique(pheno\$Taxa)
#rownames(G) = taxa
#colnames(G) = taxa

LG <- cholesky(geno) ##cholesky decomposition of genomic matrix for design matrices
ZG <- model.matrix(~0 + as.factor(pheno\$Taxa))
Z.G <- ZG %*% LG
Z.E <- model.matrix(~0 + as.factor(pheno\$Env))
ZEG <- model.matrix(~0 + as.factor(pheno\$Taxa):as.factor(pheno\$Env))
G2 <- kronecker(diag(length(unique(pheno\$Env))), data.matrix(geno))
LG2 <- cholesky(G2)
Z.EG <- ZEG %*% LG2
#Y <- as.matrix(pheno[, c('Amylose','Fat','GrossEnergy','Protein','Starch')])


nIter = 25000; burnIn = 10000
#fm <- BMTME(Y = Y, X = Z.E, Z1 = Z.G, Z2 = Z.EG, nIter = nIter, burnIn = burnIn, thin = 5, bs = 50, parallelCores=5,  progressBar = FALSE)

Total <- c()
#saveRDS(fm, '/panicle/ssapkot/GrainComp/results/BMTME/SAP_allPheno_BMTME_model.rda')
#for (i in 123:132){

    #iter <- i

    dir.create(paste0('CV-Env'))
    setwd(paste0('CV-Env'))


    #pheno2 <- data.frame(GID = pheno[, 1], Env = pheno[,4], Response = Y[,3])
    #CrossV <- CV.KFold(pheno2, DataSetID='GID', K=5, set_seed = iter)

    ETA <- list(Env = list(X = Z.E, model = 'BRR'), Gen = list(X = Z.G, model = 'BRR'), EnvGen = list(X = Z.EG, model = 'BRR'))

    #pm <- BMORS(Y, ETA = ETA, nIter = 50000, burnIn = 40000, thin = 1, progressBar = TRUE, testingSet = CrossV, digits = 4)
    dataset <- pheno[,c('Env','Amylose','Fat','Gross_Energy','Protein','Starch')]
    pm <- BMORS_Env(dataset, testingEnv = c('2013','2014','2017'), ETA = ETA, covModel = 'BayesB', nIter = 100000, burnIn = 90000, thin = 2, progressBar = TRUE, digits = 2)
    
    #res <- cbind(iter,summary(pm, information='complete'))
    #Total <- rbind(Total, res)
    
    res <- summary(pm, information='complete')
    #saveRDS(pm,file =  paste0(pop,'_BMORS_',iter,'_CV5.rds'))
    saveRDS(pm,file =  paste0(pop,'_BMORS_CV-Env.rds'))
    
    setwd('../')
    #}
    setwd('../')
write.csv(res, file=paste0(pop,'_BMORS_CV-Env.csv'), row.names=FALSE)

#saveRData(pheno, G, X, file='data/BMTME_SAP_data_GrainComp.RData')

"
echo "Finish__________________"


